### ISSUE TITLE
Validator becomes unresponsive / crashes after error

### ISSUE THREAD

**Issue by bharper-greenway** [onc-healthit/reference-ccda-validator#60]
The referenceccdaservice starts normally and will run for some time, but eventually appears to cause Tomcat to become unresponsive. A quick look at the log files makes it look like threads are not closing properly. Attached is catalina-2019-05-16.log which shows the result of a nightly restart at 3:00AM, which produced 24,566 variations of this error:
`SEVERE: The web application [/referenceccdaservice] created a ThreadLocal with key of type [java.lang.ThreadLocal] ...`

Additionally I've attached the segment of the referenceccdaservice log file that preceded the service becoming unresponsive. Tomcat was subsequently restarted (detailed information about the OS and operating environment is listed at the bottom of the catalina log file).

Apache Tomcat/7.0.76
openjdk 1.8.0_191-b12
Red Hat Enterprise Linux Server release 7.6 (3.10.0-957.5.1.el7.x86_64) 

Is this an issue related to the Tomcat configuration or this application? The issue happens with the recommended JAVA_OPTS set (currently the options are set for higher memory utilization: -Xms7G -Xmx10G -XX:PermSize=512M -XX:MaxPermSize=1024M).

Let me know if I can provide any more information. Thank you!

[catalina.2019-05-16.log](https://github.com/siteadmin/reference-ccda-validator/files/3188208/catalina.2019-05-16.log)
[referenceccdaservice.2019-05-16.log](https://github.com/siteadmin/reference-ccda-validator/files/3188209/referenceccdaservice.2019-05-16.log)

**Comment by drbgfc** [comment]
Thanks for mentioning this and sorry for the incredibly late response. This is something we should be looking into but has not been a priority. I don't think it is related to your configuration. This bug will remain open until we resolve.

**Comment by drbgfc** [comment]
I don't see the ref val log as having any relation to the stopping/mem leak issue in this case, but thanks for providing. A parsing issue should be handled fine. Any bug should be able to be handled in current form without stopping a future validation.

11:09:49,938 INFO  [ReferenceCCDAValidationService:187] Attempting Vocabulary validation...
11:10:58,409 ERROR [ReferenceCCDAValidationService:101] The service has encountered an error parsing the document. Please verify the document does not contain in-line XSL styling and/or address the fo
llowing error: org.xml.sax.SAXException: FWK005 parse may not be called while parsing.
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
        at org.sitenv.vocabularies.validation.services.VocabularyValidationService.validate(VocabularyValidationService.java:78)
        at org.sitenv.referenceccda.validators.vocabulary.VocabularyCCDAValidator.doValidation(VocabularyCCDAValidator.java:62)
        at org.sitenv.referenceccda.validators.vocabulary.VocabularyCCDAValidator.validateFileImplementation(VocabularyCCDAValidator.java:52)
        at org.sitenv.referenceccda.validators.vocabulary.VocabularyCCDAValidator.validateFile(VocabularyCCDAValidator.java:42)
        at org.sitenv.referenceccda.services.ReferenceCCDAValidationService.doVocabularyValidation(ReferenceCCDAValidationService.java:188)
        at org.sitenv.referenceccda.services.ReferenceCCDAValidationService.runValidators(ReferenceCCDAValidationService.java:128)
        at org.sitenv.referenceccda.services.ReferenceCCDAValidationService.validateCCDAImplementation(ReferenceCCDAValidationService.java:69)
        at org.sitenv.referenceccda.services.ReferenceCCDAValidationService.validateCCDA(ReferenceCCDAValidationService.java:60)
        at org.sitenv.referenceccda.controllers.ReferenceCCDAValidationController.doValidation(ReferenceCCDAValidationController.java:39)
        at org.sitenv.referenceccda.controllers.ReferenceCCDAValidationController$$FastClassBySpringCGLIB$$28bef42b.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:651)
        at org.sitenv.referenceccda.controllers.ReferenceCCDAValidationController$$EnhancerBySpringCGLIB$$508d6da4.doValidation(<generated>)
        at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:871)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

I don't think we have the same issue in production that you have found. There seem to be a lot of issues directly after startup. So, I changed my mind, it might be related to your configuraiton, versions, etc. However, regardless, I do think we have at least one potential memory leak to look into in production, even if not the same one as here.

We will see if we can reproduce.

Here is a relevant part of the log you gave for our own reference. There are plenty more leaks on startup:

SEVERE: The web application [/referenceccdaservice] registered the JDBC driver [org.hsqldb.jdbc.JDBCDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
May 16, 2019 3:01:02 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/referenceccdaservice] appears to have started a thread named [EMF Reference Cleaner] but has failed to stop it. This is very likely to create a memory leak.
May 16, 2019 3:01:02 AM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [/referenceccdaservice] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@42a85e4a]) and a value of type [org.eclipse.ocl.ecore.QueryImpl] (value [org.eclipse.ocl.ecore.QueryImpl@22ecffbd]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
May 16, 2019 3:01:02 AM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [/referenceccdaservice] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@3d248541]) and a value of type [org.eclipse.ocl.ecore.impl.ConstraintImpl] (value [context MedicationDispense inv null: self.classCode.=(vocab::ActClassSupply::SPLY)]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
May 16, 2019 3:01:02 AM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [/referenceccdaservice] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@67e44003]) and a value of type [org.eclipse.ocl.ecore.impl.ConstraintImpl] (value [context MedicationSupplyOrder2 inv null: self.templateId->exists(id : II | id.root.=('2.16.840.1.113883.10.20.22.4.17').and(id.extension.oclIsUndefined()))]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
May 16, 2019 3:01:02 AM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [/referenceccdaservice] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@2e544a97]) and a value of type [org.eclipse.ocl.ecore.impl.ConstraintImpl] (value [context ImmunizationActivity inv null: self.precondition->exists(precondition : Precondition | precondition.oclIsUndefined().not().and(precondition.oclIsKindOf(cda::Precondition)))]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
May 16, 2019 3:01:02 AM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [/referenceccdaservice] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@445cfd72]) and a value of type [org.eclipse.ocl.ecore.impl.ConstraintImpl] (value [context CarePlan inv null: self.code.oclIsUndefined().or(self.code.isNullFlavorUndefined()).implies(self.code.oclIsUndefined().not().and(self.code.oclIsKindOf(datatypes::CE)).and(let value : CE = self.code.oclAsType(datatypes::CE) in value.codeSystem.=('2.16.840.1.113883.6.1').and(value.code.=('18776-5').or(value.code.=('52521-2')).or(value.code.=('81957-3')))))]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
May 16, 2019 3:01:02 AM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [/referenceccdaservice] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@42299a02]) and a value of type [org.eclipse.ocl.ecore.QueryImpl] (value [org.eclipse.ocl.ecore.QueryImpl@7882e1c]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
May 16, 2019 3:01:02 AM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [/referenceccdaservice] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@b84dc88]) and a value of type [org.eclipse.ocl.ecore.QueryImpl] (value [org.eclipse.ocl.ecore.QueryImpl@281007e7]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
May 16, 2019 3:01:02 AM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [/referenceccdaservice] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@26e7716d]) and a value of type [org.eclipse.ocl.ecore.impl.ConstraintImpl] (value [context HealthStatusObservation2 inv null: self.templateId->exists(id : II | id.root.=('2.16.840.1.113883.10.20.22.4.5').and(id.extension.oclIsUndefined()))]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
May 16, 2019 3:01:02 AM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [/referenceccdaservice] created a ThreadLocal with key of type [org.openhealthtools.mdht.uml.cda.consol.operations.SubstanceOrDeviceAllergyObservationOperations$1] (value [org.openhealthtools.mdht.uml.cda.consol.operations.SubstanceOrDeviceAllergyObservationOperations$1@60594363]) and a value of type [org.eclipse.ocl.ecore.OCL] (value [org.eclipse.ocl.ecore.OCL@4d14b37c]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
May 16, 2019 3:01:02 AM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [/referenceccdaservice] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@6593aa06]) and a value of type [org.eclipse.ocl.ecore.impl.ConstraintImpl] (value [context ReasonForReferralSection inv null: self.code.oclIsUndefined().or(self.code.isNullFlavorUndefined()).implies(self.code.oclIsUndefined().not().and(self.code.oclIsKindOf(datatypes::CE)).and(let value : CE = self.code.oclAsType(datatypes::CE) in value.code.=('42349-1').and(value.codeSystem.=('2.16.840.1.113883.6.1'))))]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
...

**Comment by drbgfc** [comment]
We have not been able to reproduce this issue. Has it been resolved on your end yet?

**Comment by drbgfc** [comment]
Closing as unresolved
