### ISSUE TITLE
No bean named 'UnitAllowsOneValidator' is defined"

### ISSUE THREAD

**Issue by DSSUSER** [onc-healthit/reference-ccda-validator#64]
I ported the CCDA Validator project to a Docker container.

And, everything comes up properly, as expected.

However, when my development team tries to run our application against it, they are getting the following error:

"serviceErrorMessage": "The service has encountered the following error: No bean named 'UnitAllowsOneValidator' is defined".

Does anyone have any idea of what this is, or how to fix it?

**Comment by drbgfc** [comment]
That validator was added to the code validator a few months back. Is it possible you are not using the latest config file (XML) or the latest referencec validator war (which includes the latest code validator)?

**Comment by DSSUSER** [comment]
It is completely possible, as I created a Docker image a few months ago, and that is what my developers are coding against.

Is there an easy upgrade that I can run inside of my current container?

It should upgrade, just like any other application, as the filesystems were created inside of the container, just as they would normally be on a virtual machine or physical server.

Note that previously, when I built the container, our development teams were running against a virtual machine, and not the container.

Our development teams now want a second instance, to use for QA testing.

This is a new environment that I built just for testing.

Aside from the installation itself, I never tested the validator against the Docker image before.

Previously, I just wanted to know if I could build the container, without any errors.

**Comment by DSSUSER** [comment]
I just finished downloading all of the new files that you updated within the past year.

I restarted the application, and the application came up without any errors.

But, my developers are still getting the same error:    

"serviceErrorMessage": "The service has encountered the following error: No bean named 'UnitAllowsOneValidator' is defined"

Did I possibly miss something?

I downloaded each of the following files, as you can see:

20190708 18:11:24 wget https://raw.githubusercontent.com/siteadmin/reference-ccda-validator/master/configuration/ccdaReferenceValidatorConfig.xml

20190708 18:13:59 wget https://github.com/siteadmin/reference-ccda-validator/blob/bdf87aa1bb77d91f3ed940ea9ae26ebcab3d68fd/pom.xml

20190708 18:18:02 wget https://raw.githubusercontent.com/siteadmin/reference-ccda-validator/bdf87aa1bb77d91f3ed940ea9ae26ebcab3d68fd/src/main/java/org/sitenv/referenceccda/validators/vocabulary/VocabularyCCDAValidator.java

20190708 18:19:38 wget https://raw.githubusercontent.com/siteadmin/reference-ccda-validator/bdf87aa1bb77d91f3ed940ea9ae26ebcab3d68fd/src/main/java/org/sitenv/referenceccda/validators/schema/ReferenceCCDAValidator.java

20190708 18:21:23 wget https://github.com/siteadmin/reference-ccda-validator/blob/bdf87aa1bb77d91f3ed940ea9ae26ebcab3d68fd/src/main/java/org/sitenv/referenceccda/validators/BaseCCDAValidator.java

20190708 18:22:46 wget https://github.com/siteadmin/reference-ccda-validator/blob/bdf87aa1bb77d91f3ed940ea9ae26ebcab3d68fd/src/main/java/org/sitenv/referenceccda/controllers/ReferenceCCDAValidationController.java

20190708 18:24:36 wget https://github.com/siteadmin/reference-ccda-validator/blob/bdf87aa1bb77d91f3ed940ea9ae26ebcab3d68fd/src/main/java/org/sitenv/referenceccda/dto/ValidationResultsMetaData.java

20190708 18:26:12 wget https://github.com/siteadmin/reference-ccda-validator/blob/bdf87aa1bb77d91f3ed940ea9ae26ebcab3d68fd/src/main/java/org/sitenv/referenceccda/services/ReferenceCCDAValidationService.java

20190708 18:26:23 wget https://github.com/siteadmin/reference-ccda-validator/blob/bdf87aa1bb77d91f3ed940ea9ae26ebcab3d68fd/src/main/java/org/sitenv/referenceccda/services/VocabularyService.java

20190708 18:31:53 wget https://github.com/siteadmin/reference-ccda-validator/releases/download/1.0.41/referenceccdaservice.war

**Comment by DSSUSER** [comment]
After updating each of the above files, my developers are still getting the following error:

"serviceErrorMessage": "The service has encountered the following error: No bean named 'UnitAllowsOneValidator' is defined"

Any help would be greatly appreciated.

This CCDA Validator installation is running in a Docker Container.

**Comment by DSSUSER** [comment]
From the referenceccdaservice log file:

--> cd /opt/tomcat/logs

--> grep UnitAllowsOneValidator *
referenceccdaservice.2019-07-08.log:18:57:22,164 ERROR [ReferenceCCDAValidationService:100] The service has encountered the following error: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'UnitAllowsOneValidator' is defined

**Comment by drbgfc** [comment]
That line of code doesn't help much unfortunately as it just sets the service error. Thanks though - anyway, what it sounds like to me is that for some reason you don't have the latest code validator (https://github.com/siteadmin/code-validator-api). You mentioned that you replaced all the reference-ccda-validator files but not the code validator. You do have the latest war referenced though, which includes the latest code validator dependency. But, I'm not sure if that covers everything in your scenario since you also did individual source code replacements (of which I'm not sure if that's required in your case).

**Comment by drbgfc** [comment]
Basically, UnitAllowsOneValidator, is a validator that is defined in the code validator jar. It sounds to me like it doesn't exist in the code validator source you are using, for some reason. 
So, if you look here:
/codevalidator-api/src/main/java/org/sitenv/vocabularies/validation/validators/nodetypes/UnitAllowsOneValidator.java
That classs should exist in your directory.

**Comment by DSSUSER** [comment]
This particular directory structure, and class, do exist at this time.

It was missing previously.

The container starts up with just one warning that I can see:

----------------------------
20:02:00,731 INFO  [VocabularyLoadRunner:101] Value Sets loaded...
20:02:00,731 INFO  [VocabularyLoadRunner:105] !!!!*********** VOCABULARY DATABASE HAS FINISHED LOADING - SERVER WILL CONTINUE AND SHOULD BE DONE SHORTLY. ***********!!!!
20:02:00,766 INFO  [Jaxb2Marshaller:531] Creating JAXBContext by scanning packages [org.sitenv.vocabularies.configuration]
20:02:01,054 INFO  [DefaultLifecycleProcessor:341] Starting beans in phase 2147483647
20:02:01,054 INFO  [DocumentationPluginsBootstrapper:120] Context refreshed
20:02:01,115 INFO  [DocumentationPluginsBootstrapper:123] Found 1 custom documentation plugin(s)
20:02:01,169 INFO  [ApiListingReferenceScanner:44] Scanning for api listing references
20:02:01,774 INFO  [ContextLoader:347] Root WebApplicationContext: initialization completed in 543080 ms
20:02:01,807 INFO  [DispatcherServlet:489] FrameworkServlet 'dispatcher': initialization started
20:02:01,810 INFO  [AnnotationConfigWebApplicationContext:578] Refreshing WebApplicationContext for namespace 'dispatcher-servlet': startup date [Fri Jul 12 20:02:01 UTC 2019]; parent: Root WebApplicationContext
20:02:01,886 INFO  [DispatcherServlet:508] FrameworkServlet 'dispatcher': initialization completed in 78 ms
20:02:03,566 INFO  [ReferenceCCDAValidationService:180] Attempting MDHT validation...
**_20:02:03,768 WARN  [ReferenceCCDAValidator:290] An invalid validationObjective was POSTed_**
20:02:03,768 INFO  [ReferenceCCDAValidator:136] Mapped mdhtValidationObjective: NonSpecificCCDAR2
-------------------------

When the developer runs his query against this container, this is what is written in the log file:

-------------------------
20:02:09,626 INFO  [ReferenceCCDAValidator:147] Loading mdhtValidationObjective: NonSpecificCCDAR2 mapped from valdationObjective: C-CDA_IG_Plus_Vocab
20:02:26,927 INFO  [ReferenceCCDAValidator:193] ccdaVersion identified as: R2.1
20:02:26,928 INFO  [ReferenceCCDAValidator:106] Processing and returning MDHT validation results
20:02:26,964 INFO  [ReferenceCCDAValidationService:115] Adding MDHT results
20:02:26,964 INFO  [ReferenceCCDAValidationService:186] Attempting Vocabulary validation...
20:02:27,020 INFO  [VocabularyValidationService:91] Property referenceccda.isDynamicVocab is false; using preloaded default config for this and all future validations.
**_20:02:47,763 ERROR [ReferenceCCDAValidationService:100] The service has encountered the following error: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'UnitAllowsOneValidator' is defined_**
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:698)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1175)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:284)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.ServiceLocatorFactoryBean$ServiceLocatorInvocationHandler.invokeServiceLocatorMethod(ServiceLocatorFactoryBean.java:373)
        at org.springframework.beans.factory.config.ServiceLocatorFactoryBean$ServiceLocatorInvocationHandler.invoke(ServiceLocatorFactoryBean.java:363)
        at com.sun.proxy.$Proxy54.getVocabularyValidator(Unknown Source)
        at org.sitenv.vocabularies.validation.services.VocabularyValidationService.validate(VocabularyValidationService.java:106)
        at org.sitenv.vocabularies.validation.services.VocabularyValidationService.validate(VocabularyValidationService.java:69)
        at org.sitenv.referenceccda.validators.vocabulary.VocabularyCCDAValidator.doValidation(VocabularyCCDAValidator.java:60)
        at org.sitenv.referenceccda.validators.vocabulary.VocabularyCCDAValidator.validateFileImplementation(VocabularyCCDAValidator.java:49)
        at org.sitenv.referenceccda.validators.vocabulary.VocabularyCCDAValidator.validateFile(VocabularyCCDAValidator.java:39)
        at org.sitenv.referenceccda.services.ReferenceCCDAValidationService.doVocabularyValidation(ReferenceCCDAValidationService.java:187)
        at org.sitenv.referenceccda.services.ReferenceCCDAValidationService.runValidators(ReferenceCCDAValidationService.java:127)
        at org.sitenv.referenceccda.services.ReferenceCCDAValidationService.validateCCDAImplementation(ReferenceCCDAValidationService.java:68)
        at org.sitenv.referenceccda.services.ReferenceCCDAValidationService.validateCCDA(ReferenceCCDAValidationService.java:59)
        at org.sitenv.referenceccda.controllers.ReferenceCCDAValidationController.doValidation(ReferenceCCDAValidationController.java:39)
        at org.sitenv.referenceccda.controllers.ReferenceCCDAValidationController$$FastClassBySpringCGLIB$$28bef42b.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:651)
        at org.sitenv.referenceccda.controllers.ReferenceCCDAValidationController$$EnhancerBySpringCGLIB$$f6a79efb.doValidation(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)

**Comment by drbgfc** [comment]
"20:02:03,768 WARN [ReferenceCCDAValidator:290] An invalid validationObjective was POSTed" is due to user error post-startup. To locate a valid objective, send a blank validationObjective and the service will return a list of valid options. This in itself should not cause any serious errors though, as, the service (as configured now) will take an invalid objective and convert it to a default objective.

I don't understand why you are getting this error: "20:02:47,763 ERROR [ReferenceCCDAValidationService:100] The service has encountered the following error: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'UnitAllowsOneValidator' is defined" 

...with the container setup or how that would effect it. Have you tried setting it up outside of docker with a simlar environment? I mean, our environments work, but I'm not sure all the specifics of yours - so wondering if it's docker conflict or otherwise.

Sorry about the error I know it must be frustrating. It's going to take a bit of time for someone to look into it unfortunately.
