### ISSUE TITLE
1.0.41 upgrade question

### ISSUE THREAD

**Issue by DSSUSER** [onc-healthit/reference-ccda-validator#68]
For the 1.0.41 upgrade, you included a source code in ZIP format, and a source code in TAR.GZ format.

1) Do we need both source code files, or just one of the two, depending on which works best in our environment?

2) Are we supposed to simply overwrite our current directory structure with the code from these new source files, effectively overwriting any matching files that already exist in the directories?

**Comment by drbgfc** [comment]
Note: 1.0.42 is the latest.
1. The tar.gz is included by github in addition for all releases now. You only need the format you prefer, if at all.
2. If for some reason you want to view the source of a specific build vs cloning the latest repository you can download the source. It is probably best to delete everything first vs an overwrite. Normally though, one would clone the latest from the repo to attempt to build or review the source. If you want to run the application locally or on your own server, you can download the pre-built WAR.

**Comment by DSSUSER** [comment]
I installed the seven 1.0.40 updated files, and the application starts up just fine.

The 1.0.41 update includes 2 files, if I am reading your notes correctly.

If I update those 2 files manually, the application hangs and will not come up.

So, my question is this:  

1)  Do we NEED to install the source code files, overlaying what is currently installed?

2)  And, if we NEED to install the source code files, was my manual install of the 2 delivered files for nothing?

3)  Are these 2 updated files included in the newly delivered source code?

4)  Can I just copy the contents of the new source file over top of the existing directory structure?

In our environments, I have been instructed to install 1.0.41.

There was no mention of upgrading to 1.0.42 at this point in time.

Actually, the project manager just asked how long this latest 1.0.42 update had been out, and when I told her 3 days, she asked me to hold off on this latest 1.0.42 update, stopping at 1.0.41 at this time.

**Comment by drbgfc** [comment]
Generally, every github release for every project on the website (including outside of SITE) includes a package of the source. You do not need the source at all to run the application, because we have provided the WAR. It is only provided as a reference/timestamp of the source. Many projects release binaries as well so you wouldn't need the source for that either.
If you have a local instantiation setup, and you want to update it, you need to shutdown tomcat, delete the referenceccdaservice folder from your tomcat web apps folder, and delete the existing WAR from your tomcat web apps folder. Then, place the new WAR in your web apps folder and restart tomcat.
The only example of something that you might have to update (overwrite), other than the WAR, is ccdaReferenceValidatorConfig.xml. See the instructions here on how to do that https://github.com/onc-healthit/reference-ccda-validator/blob/master/README.md
Overwriting vs deleting does not matter in theory, but deleting and then copying over is usually safer as it leaves less room for human error. If it's one file, I usually overwrite, if it's a folder, I usually delete and then copy over. Make sure to copy this file over before restarting tomcat.

**Comment by DSSUSER** [comment]
After installing 1.0.40, the application built and deployed perfectly.

After installing 1.0.41, the application just sits at the following lines inside of the referenceccdaservice.log file:

        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
        ... 55 more
Caused by: java.lang.NullPointerException
        at org.sitenv.contentvalidator.configuration.ScenarioLoader.loadScenarioFiles(ScenarioLoader.java:54)
        at org.sitenv.contentvalidator.configuration.ScenarioLoader.afterPropertiesSet(ScenarioLoader.java:28)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
        ... 66 more

It just hangs here, and never goes any farther.

**Comment by drbgfc** [comment]
Can you post the full log file here?
Maybe try installing 1.0.42? I know 1.0.41 works but just as a test. Also, maybe test going back to 1.0.40 to make sure that does still work when reverting?

**Comment by DSSUSER** [comment]
After I upgraded to the 1.0.40, I saved a copy of it as an image.
I can roll back to that image at any time.
Here are the contents of the localhost log:
-------
Aug 02, 2019 1:20:24 PM org.apache.catalina.core.ApplicationContext log
INFO: Spring WebApplicationInitializers detected on classpath: [org.sitenv.referenceccda.configuration.ApplicationInitializer@337adc4c]
Aug 02, 2019 1:20:24 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
Aug 02, 2019 1:20:28 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'referenceContentValidator' defined in file [/opt/tomcat/temp/0-referenceccdaservice/WEB-INF/classes/org/sitenv/referenceccda/validators/content/ReferenceContentValidator.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.service.ContentValidatorService]: : Error creating bean with name 'contentValidatorService': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'refModelHashMap' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.configuration.ScenarioLoader]: : Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'contentValidatorService': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'refModelHashMap' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.configuration.ScenarioLoader]: : Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:446)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:328)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5179)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5704)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1018)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:994)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1127)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:2021)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'contentValidatorService': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'refModelHashMap' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.configuration.ScenarioLoader]: : Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessPropertyValues(CommonAnnotationBeanPostProcessor.java:311)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
        ... 28 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'refModelHashMap' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.configuration.ScenarioLoader]: : Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:464)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:512)
        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:486)
        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:615)
        at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:169)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessPropertyValues(CommonAnnotationBeanPostProcessor.java:308)
        ... 40 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
        ... 55 more
Caused by: java.lang.NullPointerException
        at org.sitenv.contentvalidator.configuration.ScenarioLoader.loadScenarioFiles(ScenarioLoader.java:54)
        at org.sitenv.contentvalidator.configuration.ScenarioLoader.afterPropertiesSet(ScenarioLoader.java:28)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
        ... 66 more

Aug 02, 2019 1:20:28 PM org.apache.catalina.core.ApplicationContext log
INFO: Closing Spring root WebApplicationContext
Aug 02, 2019 1:20:28 PM org.apache.catalina.core.ApplicationContext log
INFO: ContextListener: contextInitialized()
Aug 02, 2019 1:20:28 PM org.apache.catalina.core.ApplicationContext log
INFO: SessionListener: contextInitialized()
Aug 02, 2019 1:20:28 PM org.apache.catalina.core.ApplicationContext log
INFO: ContextListener: attributeAdded('StockTicker', 'async.Stockticker@2c054e23')
Aug 02, 2019 1:20:28 PM org.apache.catalina.core.ApplicationContext log
INFO: ContextListener: attributeAdded('org.apache.jasper.compiler.TldLocationsCache', 'org.apache.jasper.compiler.TldLocationsCache@57834dd8')
------------
Here are the contents of the referenceccdaservice logfile:
------------
13:20:24,961 INFO  [ContextLoader:307] Root WebApplicationContext: initialization started
13:20:25,048 INFO  [AnnotationConfigWebApplicationContext:578] Refreshing Root WebApplicationContext: startup date [Fri Aug 02 13:20:25 EDT 2019]; root of context hierarchy
13:20:25,142 INFO  [AnnotationConfigWebApplicationContext:207] Registering annotated classes: [class org.sitenv.referenceccda.configuration.MvcConfiguration,class org.sitenv.vocabularies.configuration.CodeValidatorApiConfiguration,class org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration,class org.sitenv.referenceccda.configuration.SwaggerConfig]
13:20:27,021 INFO  [DefaultListableBeanFactory:839] Overriding bean definition for bean 'propertyPlaceholderConfigurer' with a different definition: replacing [Root bean: class [org.sitenv.vocabularies.configuration.CodeValidatorApiConfiguration]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=propertyPlaceholderConfigurer; initMethodName=null; destroyMethodName=(inferred); defined in org.sitenv.vocabularies.configuration.CodeValidatorApiConfiguration] with [Root bean: class [org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=propertyPlaceholderConfigurer; initMethodName=null; destroyMethodName=(inferred); defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration]
13:20:27,836 INFO  [PostProcessorRegistrationDelegate$BeanPostProcessorChecker:328] Bean 'org.springframework.cache.annotation.ProxyCachingConfiguration' of type [class org.springframework.cache.annotation.ProxyCachingConfiguration$$EnhancerBySpringCGLIB$$dbffa733] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
13:20:28,130 WARN  [AnnotationConfigWebApplicationContext:546] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'referenceContentValidator' defined in file [/opt/tomcat/temp/0-referenceccdaservice/WEB-INF/classes/org/sitenv/referenceccda/validators/content/ReferenceContentValidator.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.service.ContentValidatorService]: : Error creating bean with name 'contentValidatorService': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'refModelHashMap' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.configuration.ScenarioLoader]: : Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'contentValidatorService': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'refModelHashMap' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.configuration.ScenarioLoader]: : Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:446)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:328)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5179)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5704)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1018)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:994)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1127)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:2021)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'contentValidatorService': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'refModelHashMap' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.configuration.ScenarioLoader]: : Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessPropertyValues(CommonAnnotationBeanPostProcessor.java:311)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
        ... 28 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'refModelHashMap' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.configuration.ScenarioLoader]: : Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:464)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:512)
        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:486)
        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:615)
        at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:169)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessPropertyValues(CommonAnnotationBeanPostProcessor.java:308)
        ... 40 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
        ... 55 more
Caused by: java.lang.NullPointerException
        at org.sitenv.contentvalidator.configuration.ScenarioLoader.loadScenarioFiles(ScenarioLoader.java:54)
        at org.sitenv.contentvalidator.configuration.ScenarioLoader.afterPropertiesSet(ScenarioLoader.java:28)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
        ... 66 more
---------------
This is where it just stops...
And, I see the errors in the logs, but I don't know how to fix them, or what may be wrong with them.
